version: '3'

services:

  db_server:
    image: mysql:latest
    container_name: mysql_server
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'energy-db'
       
  energy_platform_server:
    image: tomcat
    container_name: tomcat_app_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db_server

  react_app:
    image: react
    container_name: react_frontend
    ports:
      - "3000:3000"
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - energy_platform_server
